{
  pkgs,
  ...
}:
{
  home.packages = with pkgs; [
    calibre
    #ciscoPacketTracer8-fix
    cisco-packet-tracer_9-fix
    cmatrix
    firefox
    gimp3
    gparted
    inkscape
    itch
    kdePackages.ark
    kitty
    libreoffice
    makemkv
    mangohud
    mgba
    mpv
    nur.repos.workman-nur.ninvaders-workman
    nur.repos.workman-nur.tetris-workman
    pipes-rs
    prismlauncher
    qbittorrent
    stable.kicad
    stable.minicom
    rose-pine-hyprcursor
    rose-pine-cursor
    teams-for-linux
    telegram-desktop
    thorium-reader
    ungoogled-chromium
    ventoy
    vlc
    freecad-wayland
  ];
}
