{ pkgs, ... }: {
  home.packages = with pkgs; [
    bottles
    cmatrix
    firefox
    gimp3
    gparted
    hyprland
    inkscape
    kdePackages.ark
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    kicad
    kitty
    libreoffice
    makemkv
    mangohud
    minicom
    mpv
    nur.repos.nltch.ciscoPacketTracer8
    nur.repos.workman-nur.ninvaders-workman
    nur.repos.workman-nur.tetris-workman
    pipes-rs
    prismlauncher
    swww
    teams-for-linux
    telegram-desktop
    ungoogled-chromium
    ventoy
    vlc
  ];
}
