# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
 # imports = [
 #   (modulesPath + "/installer/scan/not-detected.nix")
 # ];

 # boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid" "sdhci_pci"];
 # boot.initrd.kernelModules = [];
 # boot.kernelModules = ["kvm-amd"];
 # boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e433f930-5c0a-420a-9b7c-a71db3f4955c";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7417-6628";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/78621bdb-dc59-43b2-949b-ddb207e0e65e";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.vboxnet0.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethcNxmLB.useDHCP = lib.mkDefault true;
  # networking.interfaces.waydroid0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

 # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
 # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
